//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawn.Core.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PawnEntities : DbContext
    {
        public PawnEntities()
            : base("name=PawnEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Account> Tb_Account { get; set; }
        public virtual DbSet<Tb_Account_Store> Tb_Account_Store { get; set; }
        public virtual DbSet<Tb_AccountType> Tb_AccountType { get; set; }
        public virtual DbSet<Tb_BH_Pay> Tb_BH_Pay { get; set; }
        public virtual DbSet<Tb_BHContract> Tb_BHContract { get; set; }
        public virtual DbSet<Tb_Capital> Tb_Capital { get; set; }
        public virtual DbSet<Tb_Capital_Loan> Tb_Capital_Loan { get; set; }
        public virtual DbSet<Tb_Capital_PayDay> Tb_Capital_PayDay { get; set; }
        public virtual DbSet<Tb_Contract> Tb_Contract { get; set; }
        public virtual DbSet<Tb_Customer> Tb_Customer { get; set; }
        public virtual DbSet<Tb_DebitContract> Tb_DebitContract { get; set; }
        public virtual DbSet<Tb_Debt> Tb_Debt { get; set; }
        public virtual DbSet<Tb_DiscoutHeadMoney> Tb_DiscoutHeadMoney { get; set; }
        public virtual DbSet<Tb_Document> Tb_Document { get; set; }
        public virtual DbSet<Tb_ExtentionContract> Tb_ExtentionContract { get; set; }
        public virtual DbSet<Tb_FileManagement> Tb_FileManagement { get; set; }
        public virtual DbSet<Tb_History> Tb_History { get; set; }
        public virtual DbSet<Tb_IncomeAndExpense> Tb_IncomeAndExpense { get; set; }
        public virtual DbSet<Tb_InfoInstallment> Tb_InfoInstallment { get; set; }
        public virtual DbSet<Tb_InterestPay> Tb_InterestPay { get; set; }
        public virtual DbSet<Tb_Menu> Tb_Menu { get; set; }
        public virtual DbSet<Tb_MenuPermission> Tb_MenuPermission { get; set; }
        public virtual DbSet<Tb_MoreLoan> Tb_MoreLoan { get; set; }
        public virtual DbSet<Tb_PawnContract> Tb_PawnContract { get; set; }
        public virtual DbSet<Tb_PawnPay> Tb_PawnPay { get; set; }
        public virtual DbSet<Tb_Role> Tb_Role { get; set; }
        public virtual DbSet<Tb_Status> Tb_Status { get; set; }
        public virtual DbSet<Tb_StatusContract> Tb_StatusContract { get; set; }
        public virtual DbSet<Tb_Store> Tb_Store { get; set; }
        public virtual DbSet<Tb_Timer> Tb_Timer { get; set; }
        public virtual DbSet<Tb_User> Tb_User { get; set; }
        public virtual DbSet<Tb_UserRole> Tb_UserRole { get; set; }
        public virtual DbSet<Tb_UserRoleAdmin> Tb_UserRoleAdmin { get; set; }
        public virtual DbSet<Tb_Voucher> Tb_Voucher { get; set; }
        public virtual DbSet<Tb_CashBook> Tb_CashBook { get; set; }
    }
}
