//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawn.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Contract
    {
        public int Id { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<double> PaymentMoney { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> PaymentNumberDay { get; set; }
        public Nullable<int> PeriodInterest { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string Note { get; set; }
        public string Collateral { get; set; }
        public Nullable<double> InterestRate { get; set; }
        public Nullable<int> TypeInterestRate { get; set; }
        public Nullable<int> FormInterestRate { get; set; }
        public Nullable<bool> IsFirstInterestRate { get; set; }
        public Nullable<bool> IsCloseContract { get; set; }
        public Nullable<System.DateTime> CloseContractDate { get; set; }
        public string CloseContractUser { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DeletedUser { get; set; }
    }
}
