//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawn.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Capital_Loan
    {
        public int Id { get; set; }
        public int CapitalId { get; set; }
        public System.DateTime LoadDate { get; set; }
        public decimal MoneyNumber { get; set; }
        public string Note { get; set; }
        public string CreatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsLoan { get; set; }
        public Nullable<int> DocumentType { get; set; }
    }
}
