//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawn.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Customer
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string Fullname { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public Nullable<int> StatusId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public string DeletedUser { get; set; }
        public bool IsActive { get; set; }
        public string IdentityCard { get; set; }
        public string ICCreateDate { get; set; }
        public string ICCreatePlace { get; set; }
    }
}
