//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawn.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_FileManagement
    {
        public int Id { get; set; }
        public int ContractId { get; set; }
        public int ContractType { get; set; }
        public string FileName { get; set; }
        public string FileGuild { get; set; }
        public string Ext { get; set; }
        public Nullable<int> FileSize { get; set; }
        public Nullable<int> FileType { get; set; }
        public string Url { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public string UpdatedUser { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<int> DocumentType { get; set; }
    }
}
