//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawn.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_History
    {
        public int Id { get; set; }
        public Nullable<int> ContractID { get; set; }
        public Nullable<int> TypeHistory { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> DebitMoney { get; set; }
        public Nullable<decimal> HavingMoney { get; set; }
        public string Content { get; set; }
        public Nullable<int> StoreId { get; set; }
    }
}
