//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawn.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_PawnContract
    {
        public int Id { get; set; }
        public int StoreId { get; set; }
        public int CustomerId { get; set; }
        public double TotalMoney { get; set; }
        public string Collateral { get; set; }
        public double InterestRate { get; set; }
        public Nullable<int> InterestRateType { get; set; }
        public bool IsBefore { get; set; }
        public Nullable<int> InterestRateOption { get; set; }
        public Nullable<int> PawnDateNumber { get; set; }
        public Nullable<int> InterestRateNumber { get; set; }
        public System.DateTime PawnDate { get; set; }
        public string Note { get; set; }
        public bool IsCloseContract { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public string ClosedUser { get; set; }
        public bool IsDeleted { get; set; }
        public string DeletedUser { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string UpdatedUser { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public string Code { get; set; }
        public string DocumentName { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public Nullable<System.DateTime> DocumentDate { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsBadDebt { get; set; }
        public Nullable<decimal> MoneyServices { get; set; }
        public Nullable<decimal> MoneyIntroduce { get; set; }
        public Nullable<int> StaffManagerId { get; set; }
    }
}
