//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pawn.Core.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_PawnPay
    {
        public int Id { get; set; }
        public int ContractId { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public Nullable<System.DateTime> LoanDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public bool IsPaid { get; set; }
        public Nullable<decimal> InterestMoney { get; set; }
        public Nullable<decimal> OtherMoney { get; set; }
        public Nullable<decimal> CustomerMoney { get; set; }
        public Nullable<int> TotalDay { get; set; }
    }
}
